# Generated by Django 3.2.9 on 2021-11-23 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='GenreId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylibrary.genres'),
        ),
    ]
