# Generated by Django 3.2.9 on 2021-11-23 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mylibrary', '0002_alter_books_genreid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='AuthorId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylibrary.authors'),
        ),
        migrations.AlterField(
            model_name='books',
            name='PublisherId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mylibrary.publishers'),
        ),
    ]
